### ISSUE TITLE
ROUND | Option to disable rounded corners of the download tab

### ISSUE THREAD

**Issue by OuterWinnie** [EMERALD0874/Steam-Deck-Themes#22]
Hi, i would like an option to disable the rounded corners of the download tab, it doesn't look right as it is now.

It fills the space made it by rounding the borders, with black on the background image (red) and the selected game effect looks weird too (yellow):
https://i.imgur.com/Q0AnZt4.jpg

Also, only the left part of the background image is being rounded, the right one doesn't seem to be rounding:
https://i.imgur.com/nxJQvta.jpg

Thanks! Loving your theme otherwise!

**Comment by EMERALD0874** [comment]
Regarding the red ovals, those definitely look to be bugs. I'll look into that right now. The yellow ovals were intentional, but I agree that it does look a little odd when selecting the first element of the list. I'll go ahead and look into that, as well.

**Comment by EMERALD0874** [comment]
The theme now looks like this. Completed, up next, and scheduled downloads are still rounded since they do not take up the entire width of the screen. Does this resolve your issue, @OuterWinnie?

![image](https://user-images.githubusercontent.com/11338953/183222222-4f9f80c4-cdcd-45f7-a100-6bcfd32f6e95.png)
![image](https://user-images.githubusercontent.com/11338953/183222210-95e532f5-6976-4d52-b768-9cfaa3b44626.png)

**Comment by OuterWinnie** [comment]
That's more than enought, your amazing! Thanks!
